---
apiVersion: v1
kind: Service
metadata:
  name: web-echo
spec:
  selector:
    app: nginx
  sessionAffinity: None
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  - port: 443
    protocol: TCP
    targetPort: 443
